/*******************************************************************
Do not edit this file in any way.
Just close it and look at a different file.
********************************************************************/

public abstract class CacheSim
{
	private Memory main;
	protected Memory keys;
	protected Memory vals;

	private int caches;
	private int saves;

	public CacheSim(int memsize, int cachesize)
	{
		main = new Memory(memsize,0);
		keys = new Memory(cachesize,-1);
		vals = new Memory(cachesize,0);
		caches = saves = 0;
	}

	abstract int read(int address);
	abstract void write(int address, int value);
	abstract void uncache();

	public void cache(int mainaddr, int cacheaddr)
	{
		caches++;
		keys.write(cacheaddr,mainaddr);
		vals.write(cacheaddr,main.read(mainaddr));
	}

	public void save(int cacheaddr)
	{
		saves++;
		main.write(keys.read(cacheaddr),vals.read(cacheaddr));
	}

	public void report()
	{
		uncache();
		System.out.println("Cache Sim Report:");
		System.out.println("Main Memory Size:  "+main.getSize());
		System.out.println("Cache Memory Size: "+keys.getSize());
		System.out.println("Caches: "+caches);
		System.out.println("Saves:  "+saves);
	}

	public void fullreport()
	{
		report();
		System.out.println("Main: "+main);
		System.out.println("Keys: "+keys);
		System.out.println("Vals: "+vals);
	}
}
