/*******************************************************************
Do not edit this file in any way.
Just close it and look at a different file.
********************************************************************/

import java.util.Arrays;

public class Memory
{
	private int[] memory;

	public Memory(int memsize, int fill)
	{
		memory = new int[memsize];
		Arrays.fill(memory,fill);
	}

	public int read(int address)
	{
		if(address<0) return -1;
		if(address>=memory.length) return -1;
		return memory[address];
	}

	public int write(int address, int value)
	{
		if(address<0) return -1;
		if(address>=memory.length) return -1;
		if(value<0) return -1;
		memory[address]=value;
		return value;
	}

	public int getSize() { return memory.length; }

	public String toString()
	{
		String ret = "";
		for(int i=0; i<memory.length; i++)
		{
			if(!ret.equals("")) ret+="\t";
			ret+= memory[i];
		}
		return ret;
	}
}